<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Contact</name>
   <tag></tag>
   <elementGuidId>7ba903c7-3511-4679-86f2-b6304df9ce3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(6) > a.nav-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Contact')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9879a989-f53a-40fb-9fb1-83606cd6a88e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/contact-us</value>
      <webElementGuid>13549aff-74d0-4bdb-8785-c0dd731ce7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>c630cfc8-45aa-46cb-9237-4fb55a3b9b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact</value>
      <webElementGuid>0272be0c-6856-4c24-9c9c-56c37139ed8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;w-mod-js w-mod-ix wf-archivo-n6-active wf-archivo-n3-active wf-archivo-n4-active wf-archivo-n5-active wf-montserrat-n7-active wf-montserrat-n9-active wf-montserrat-n3-active wf-montserrat-n6-active wf-montserrat-n8-active wf-montserrat-n2-active wf-montserrat-n4-active wf-montserrat-n5-active wf-montserrat-n1-active wf-montserrat-i2-active wf-montserrat-i5-active wf-montserrat-i3-active wf-montserrat-i4-active wf-montserrat-i9-active wf-montserrat-i8-active wf-montserrat-i7-active wf-montserrat-i1-active wf-montserrat-i6-active wf-active wf-instrumentsans-n4-active&quot;]/body[@class=&quot;body loader-init dark-header loader-hide loaded&quot;]/div[@class=&quot;navbar-logo-left&quot;]/div[@class=&quot;navbar-logo-left-container shadow-three no-bg desktop-header w-nav&quot;]/div[@class=&quot;container-x&quot;]/div[@class=&quot;navbar-wrapper&quot;]/nav[@class=&quot;nav-menu-wrapper w-nav-menu&quot;]/ul[@class=&quot;nav-menu-two w-list-unstyled&quot;]/li[6]/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>04ba0e3e-e8c5-4676-9d14-5989d15c66d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Contact')]</value>
      <webElementGuid>b9326cf6-58cc-4939-9ba4-47e2c04d9c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/contact-us')]</value>
      <webElementGuid>5d3310f1-e022-44a4-abff-28e345edc43c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>bff6999d-059a-4051-ba90-395bb6766eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/contact-us' and (text() = 'Contact' or . = 'Contact')]</value>
      <webElementGuid>efb79e8e-0f51-4712-b300-c95dd21a0c1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
