<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_003  545Watch full videoLive</name>
   <tag></tag>
   <elementGuidId>9fe1f78d-395c-4d83-94da-6b7b470dc393</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ytp-inline-preview-scrim</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='inline-preview-player']/div[20]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>259ca4e4-7557-4e86-aef8-f416e3ac9486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ytp-inline-preview-scrim</value>
      <webElementGuid>2f14b67d-92bb-4d74-aeeb-76c1aa4e4dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0:03 / 5:45•Watch full videoLive</value>
      <webElementGuid>e9652e7b-0e35-48bd-abb4-824f76925af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inline-preview-player&quot;)/div[@class=&quot;ytp-inline-preview-ui&quot;]/div[@class=&quot;ytp-inline-preview-scrim&quot;]</value>
      <webElementGuid>6bbab7d4-03b4-4ee8-ae03-e1e1514544e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inline-preview-player']/div[20]/div</value>
      <webElementGuid>fe9e52e8-44c8-4bf9-b131-be8af1b4517a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/ytd-player/div/div/div[20]/div</value>
      <webElementGuid>0fa0fb85-cd8f-4bb0-82ed-30e580e6205e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '0:03 / 5:45•Watch full videoLive' or . = '0:03 / 5:45•Watch full videoLive')]</value>
      <webElementGuid>d73b1399-c2d1-4b77-a546-9b983b6e9fed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
