<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tenementNo</name>
   <tag></tag>
   <elementGuidId>f8be65cb-d0a3-48a3-9fed-59f11b663444</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tenementNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tenementNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dfc72ebf-196e-496c-9656-e5e5a1498c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>81a5ef68-ea96-4be9-977d-0d24989a00ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Tenement No is required.</value>
      <webElementGuid>87a986eb-1a0b-4a13-ab3f-5f94718385b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tenementNo</value>
      <webElementGuid>830497e8-6920-407e-8af6-7be7579a2a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tenementNo</value>
      <webElementGuid>5bae8e2c-dcf4-4427-9650-41380e02f798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>InputToUpper(this);</value>
      <webElementGuid>f2a46a7f-0d37-4ead-8a64-ca5cc70e5236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1c22e060-d828-4587-ab86-d4852d8fa1bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tenementNo&quot;)</value>
      <webElementGuid>f0f874e4-0857-4f4a-8891-3145c50778a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tenementNo']</value>
      <webElementGuid>f269ffb4-c75a-487f-b46b-ecfc1e0463bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-2609']/div[2]/div/div/div[2]/div/div[2]/form/div/div/div/div/div/input</value>
      <webElementGuid>5e442609-813e-48e0-8591-a61d34823a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d28fb6ed-8f85-4912-963d-548c0b39e934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tenementNo' and @name = 'tenementNo' and @type = 'text']</value>
      <webElementGuid>449f1e8f-1c8e-44a7-87ca-179166ea5f98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
