<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__2o9o_t</name>
   <tag></tag>
   <elementGuidId>0a91b2e4-ed67-4ed7-aa11-3f215d1abc69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button._5GBmrW > span._2o9o_t</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/button[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0cf4f05f-179a-4503-a19a-01fdda99e611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_2o9o_t</value>
      <webElementGuid>d7421db7-83b3-4d81-9461-aec9985c10e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;q8WwEU&quot;]/div[@class=&quot;_3zsGrb&quot;]/div[@class=&quot;_2-LWwB&quot;]/div[1]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-1udh08x&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-1iqfa7g r-60vfwk&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-1iqfa7g r-60vfwk&quot;]/div[@class=&quot;_1ui5b4&quot;]/div[@class=&quot;yAlKeh&quot;]/div[@class=&quot;_2L0uxW&quot;]/div[@class=&quot;_3116_u&quot;]/div[@class=&quot;_1yQHx8 _2UnIQ_ _3ak8Rd _2y8Yzt&quot;]/div[1]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-13awgt0 r-eqz5dr&quot;]/div[1]/div[1]/div[@class=&quot;_3n8fnaug _3n8fnamv _3n8fnaf9 _3n8fna1 _3n8fna7n _1i2djtb9 _1i2djt0 _9nihix1c&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;_2tczCl&quot;]/button[@class=&quot;_5GBmrW&quot;]/span[@class=&quot;_2o9o_t&quot;]</value>
      <webElementGuid>e3655c5d-265b-44cc-b24b-93e21eea2dec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/button[2]/span</value>
      <webElementGuid>520725c3-7ee7-4917-a225-6d362f41f639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>88b86a9c-6aeb-45bc-bf73-1104cf725284</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
