<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_home-icon-large-off menu-icon</name>
   <tag></tag>
   <elementGuidId>2a98b58d-33de-458a-8d8d-d950ef765229</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#web > a > span.home-icon-large-off.menu-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='web']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4515d4cd-7674-421f-a111-4d98aaf9283d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>home-icon-large-off menu-icon</value>
      <webElementGuid>d3c39bf1-205a-43f0-807b-971a9594ec67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;lp-page-children bp-area --area&quot;]/div[@class=&quot;bp-widget bp-ui-dragRoot&quot;]/div[@class=&quot;bp-widget-body ng-scope&quot;]/div[1]/div[@class=&quot;bp-g-model&quot;]/div[@class=&quot;quick-navbar middle-quick-menus top-stick-menus navbar-available&quot;]/div[@class=&quot;row full-width-bg ng-scope&quot;]/div[@class=&quot;lp-navbar-advanced container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;middle-menu-bar navbar navbar-inverse navbar-static-top&quot;]/div[1]/div[@class=&quot;navbar-collapse collapse&quot;]/ul[@class=&quot;nav navbar-nav lp-navbar-advanced-root personal-navbar&quot;]/li[@id=&quot;web&quot;]/a[1]/span[@class=&quot;home-icon-large-off menu-icon&quot;]</value>
      <webElementGuid>a3326d26-c159-490d-8990-88ba54e83c12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='web']/a/span</value>
      <webElementGuid>48bc7dbc-f65b-4938-94ef-f5516fdbf906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div[2]/ul/li/a/span</value>
      <webElementGuid>dd9a9646-585a-40e5-8825-0688e3123859</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
