<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Invalid username or password</name>
   <tag></tag>
   <elementGuidId>3d75fdd6-a875-4427-a569-b92f2ccfe844</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.bs-input-label-suffix</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[9]/div[2]/div/form/div/div/div/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e8db748a-a4a4-4624-a12f-e4b38e91e185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bs-input-label-suffix</value>
      <webElementGuid>6e22eeaf-f585-47c7-b7a4-8c04a8093a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid username or password</value>
      <webElementGuid>2b6ec989-0d31-4964-a985-1ccce18e0af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;auth&quot;]/div[@class=&quot;auth-wrapper&quot;]/div[@class=&quot;auth-container&quot;]/form[@class=&quot;auth-container--form&quot;]/div[@class=&quot;auth-form-row&quot;]/div[@class=&quot;auth-form-input email&quot;]/div[@class=&quot;bs-input-container input--container&quot;]/label[@class=&quot;bs-input-label-suffix&quot;]</value>
      <webElementGuid>2bcdcc07-ffa5-4a4d-9779-0f977da31ebb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[9]/div[2]/div/form/div/div/div/label[2]</value>
      <webElementGuid>9aa7944a-ac21-435e-9953-baaffd029683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>6b963b55-fefd-4e1c-9874-d4c40aacbd11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Invalid username or password' or . = 'Invalid username or password')]</value>
      <webElementGuid>52ea7dff-d5bf-4633-a300-e94913d39432</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
