<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Smartphones  Basic Mobiles</name>
   <tag></tag>
   <elementGuidId>2ae6ea4a-259c-41dc-b80d-8ea08a385c79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='s-refinements']/div/ul/li[6]/span/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>902c7126-bb5f-4309-805c-81072156d1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>b9528bb0-a3ce-4892-beec-dedab94eace9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Smartphones &amp; Basic Mobiles</value>
      <webElementGuid>f21fc7fe-76b3-4381-adfd-85dea8142061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s-refinements&quot;)/div[@class=&quot;a-section a-spacing-none&quot;]/ul[@class=&quot;a-unordered-list a-nostyle a-vertical a-spacing-medium&quot;]/li[@class=&quot;a-spacing-micro apb-browse-refinements-indent-2&quot;]/span[@class=&quot;a-list-item&quot;]/a[@class=&quot;a-color-base a-link-normal&quot;]/span[1]</value>
      <webElementGuid>b5c09ad0-e549-4f9c-bfdd-6181e4a88d46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='s-refinements']/div/ul/li[6]/span/a/span</value>
      <webElementGuid>48f81351-1c10-4594-9efd-bd188eab8238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/span/a/span</value>
      <webElementGuid>da8310d8-39c5-4d6c-bc79-34f394de6967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Smartphones &amp; Basic Mobiles' or . = 'Smartphones &amp; Basic Mobiles')]</value>
      <webElementGuid>7a197fe6-a63e-49ee-b803-f6bca854ea90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
