<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_click-area_1_2</name>
   <tag></tag>
   <elementGuidId>7a419f1a-e6a5-40f2-ba21-7ff2450d71a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(4) > button.slick-dot > i.click-area</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/div/div/ul/li[4]/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bfbc5518-ad27-4ec3-8716-d8211e7168df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>click-area</value>
      <webElementGuid>92854e31-b6b3-4a7e-91cc-0277f8402c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;c-main-carousel&quot;]/div[@class=&quot;container container--custom&quot;]/div[@class=&quot;slick-slider slick-initialized&quot;]/ul[@class=&quot;slick-dots&quot;]/li[4]/button[@class=&quot;slick-dot&quot;]/i[@class=&quot;click-area&quot;]</value>
      <webElementGuid>8a17fc07-de58-47cb-b78a-6445e2656865</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div/div/ul/li[4]/button/i</value>
      <webElementGuid>64971bcc-4a82-4dba-baa1-257a18b3b79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/button/i</value>
      <webElementGuid>9d74f546-99e2-4861-9644-d12952a7df72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
