<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_click-area</name>
   <tag></tag>
   <elementGuidId>096d95d6-628f-4701-8041-245e50ff92b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > button.slick-dot > i.click-area</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/div/div/ul/li[2]/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>155afb0b-8dc7-4a1b-9114-49ae7b47fe3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>click-area</value>
      <webElementGuid>cbe8ab16-4568-4f89-b335-3fa181e8bec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;c-main-carousel&quot;]/div[@class=&quot;container container--custom&quot;]/div[@class=&quot;slick-slider slick-initialized&quot;]/ul[@class=&quot;slick-dots&quot;]/li[2]/button[@class=&quot;slick-dot&quot;]/i[@class=&quot;click-area&quot;]</value>
      <webElementGuid>e8de2e1c-c476-4b0b-a212-25a25558c462</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div/div/ul/li[2]/button/i</value>
      <webElementGuid>dcb51c8c-2d01-4049-938b-c1f2b3b1dc2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/button/i</value>
      <webElementGuid>0e24caf1-0260-4df7-bcbc-ff69ff14ec03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
