<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_scroll-down__chevron-down is-en-txt</name>
   <tag></tag>
   <elementGuidId>8d34b96f-c8b7-411a-86d0-20726a8faea8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.scroll-down__chevron-down.is-en-txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='scrollDown']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0c6daffe-6ce1-4a82-844f-49358e173d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>scroll-down__chevron-down is-en-txt</value>
      <webElementGuid>38ed0684-90f4-4802-9f87-88cef5237ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollDown&quot;)/i[@class=&quot;scroll-down__chevron-down is-en-txt&quot;]</value>
      <webElementGuid>e1df1ef3-04ad-42d9-8f0e-5302d6bc5830</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='scrollDown']/i</value>
      <webElementGuid>096d232b-42d6-49f2-b11b-61e62552b90a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>6c42b4dc-a373-4509-81f6-2b2f53269572</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
