<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sequence created successfully</name>
   <tag></tag>
   <elementGuidId>522aae72-9aaa-4719-a88b-3a2cb73f38b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.message-desc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[7]/div[2]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f35ed08e-d512-4c59-b80b-7606dbcd1974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>message-desc</value>
      <webElementGuid>fe55d5dd-045c-46b0-96c9-a2a009f07838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sequence created successfully</value>
      <webElementGuid>085f2a4e-df24-4e3a-992d-4bb173dbda61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bs-message-container&quot;]/div[@class=&quot;bs-message bottom&quot;]/div[@class=&quot;fade toast message-container theme-new variant-success regular-2 show&quot;]/div[@class=&quot;message-desc&quot;]</value>
      <webElementGuid>8fd3360f-dfee-42a1-9edd-3ebb692cd1e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[7]/div[2]/div/div[2]</value>
      <webElementGuid>4edf55f6-ca5d-4323-a25b-bea9c8da6b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>f506b1a4-59c9-42cd-ab89-bf556ed84eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sequence created successfully' or . = 'Sequence created successfully')]</value>
      <webElementGuid>4a4d8860-f4d7-48ae-aee1-3a7aeec20f04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
