<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>c770135e-845b-410c-b493-079e1581f58a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.jss432.heartIcon > svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>19da930c-d3fb-4779-b693-e7b71592b8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>version</name>
      <type>Main</type>
      <value>1.1</value>
      <webElementGuid>cfc0d3f4-7e62-4cad-a88f-4910b01c6de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xlink</name>
      <type>Main</type>
      <value>http://www.w3.org/1999/xlink</value>
      <webElementGuid>4a44d98f-7a0d-45fe-a57a-ca433a450c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>88b8157a-f459-483b-8160-dae8444676b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>36cf20ef-aee5-40f5-95a6-515f69670696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>78e2fba3-4d8c-4641-809c-ca2900ece085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>3 4 18 16</value>
      <webElementGuid>851d77d1-f2d7-4387-93bd-f7c0b9f61d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>rgba(32, 29, 29, 0.2)</value>
      <webElementGuid>6a895484-e0a9-494c-9fd6-0d424dc6c01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_46479c0a28cf4dd7bf328541877b0b26&quot;)/li[@class=&quot;jss357 jss372&quot;]/div[@class=&quot;listItemContainer&quot;]/div[@class=&quot;jss430&quot;]/div[@class=&quot;jss431&quot;]/span[@class=&quot;jss432 heartIcon&quot;]/svg[1]</value>
      <webElementGuid>6f662590-2b65-4ab0-b0cd-d86d919ec562</webElementGuid>
   </webElementProperties>
</WebElementEntity>
