<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_FavoriteBorderIcon</name>
   <tag></tag>
   <elementGuidId>a518e69d-c7b1-4e9e-8bd9-fba00119db26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg[name=&quot;FavoriteBorderIcon&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//svg[@name = 'FavoriteBorderIcon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>db10f6ae-fa3d-4cfe-839b-466653cc022a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiSvgIcon-root</value>
      <webElementGuid>02a842d0-030e-461d-a746-1c6a117a2f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cea27b4d-9b4c-4a93-a6b4-552d0bbff177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>d43635eb-ab3e-4b7f-a55b-7e37dfb77bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2b7f6bfa-35ec-40bf-93e6-415ab7608cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FavoriteBorderIcon</value>
      <webElementGuid>c5a2adf6-08a5-420d-868e-374217b19d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;header-banner jss8&quot;]/section[@class=&quot;MuiContainer-root&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthXl jss25&quot;]/header[@class=&quot;MuiPaper-root MuiAppBar-root jss26 false MuiAppBar-positionAbsolute MuiAppBar-colorSecondary MuiPaper-elevation0&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-root jss17&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-root jss17 jss19 MuiGrid-container MuiGrid-container MuiGrid-align-items-xs-center MuiGrid-align-items-xs-center&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-root jss46 MuiGrid-item MuiGrid-item MuiGrid-grid-sm-10 MuiGrid-grid-sm-10&quot;]/div[@class=&quot;jss32&quot;]/div[@class=&quot;jss35&quot;]/div[@class=&quot;favorite-section-wrapper&quot;]/div[@class=&quot;jss289&quot;]/button[@class=&quot;MuiButtonBase-root MuiIconButton-root undefined jss297 jss298 MuiIconButton-edgeStart&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/span[@class=&quot;MuiBadge-root&quot;]/svg[@class=&quot;MuiSvgIcon-root&quot;]</value>
      <webElementGuid>7cb21f56-1b59-45f5-82ce-2e11c6412196</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[@name = 'FavoriteBorderIcon']</value>
      <webElementGuid>c7e0fa1c-3938-43ff-b2d5-c681280de868</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
