<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_client-c-logo</name>
   <tag></tag>
   <elementGuidId>15922d63-a736-488f-afbd-e289fb7ad260</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://assets-global.website-files.com/64feb7c4af2e29e2463d3f48/652e2731844d3645bb40eebc_image%20287.jpg')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>41b3bb0c-a6e4-4693-9d10-99af073891df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets-global.website-files.com/64feb7c4af2e29e2463d3f48/652e2731844d3645bb40eebc_image%20287.jpg</value>
      <webElementGuid>74fd0b7f-d10c-4be8-9cdc-27f9cb86683f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>client-c-logo</value>
      <webElementGuid>06fb975d-bad4-4320-9975-f6cc20954190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;w-mod-js wf-montserrat-n1-active wf-montserrat-i1-active wf-montserrat-n2-active wf-montserrat-i2-active wf-montserrat-n3-active wf-montserrat-i3-active wf-montserrat-n4-active wf-montserrat-i4-active wf-montserrat-n5-active wf-montserrat-i5-active wf-montserrat-n6-active wf-montserrat-i6-active wf-montserrat-n7-active wf-montserrat-i7-active wf-montserrat-n8-active wf-montserrat-i8-active wf-montserrat-n9-active wf-montserrat-i9-active wf-archivo-n3-active wf-archivo-n4-active wf-archivo-n5-active wf-archivo-n6-active wf-active w-mod-ix wf-instrumentsans-n4-active&quot;]/body[@class=&quot;contact-body loader-init loader-hide loaded&quot;]/section[@class=&quot;contact-page-form section-py&quot;]/div[@class=&quot;container-x&quot;]/div[@class=&quot;contact-form-row&quot;]/div[@class=&quot;contact-form-col1&quot;]/div[@class=&quot;contact-client-logos-c&quot;]/div[@class=&quot;w-layout-hflex contact-client-logos&quot;]/img[@class=&quot;client-c-logo&quot;]</value>
      <webElementGuid>f9b249cd-82c6-4d4f-9e7a-ee6838e4ed72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://assets-global.website-files.com/64feb7c4af2e29e2463d3f48/652e2731844d3645bb40eebc_image%20287.jpg')]</value>
      <webElementGuid>37537ba4-1d30-4d31-bb06-a2c4df73c801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[7]</value>
      <webElementGuid>7f5ed6dd-da64-44ab-9883-1414d159c446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets-global.website-files.com/64feb7c4af2e29e2463d3f48/652e2731844d3645bb40eebc_image%20287.jpg']</value>
      <webElementGuid>e2ace930-076b-44c6-9785-05517ea164e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
