<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__2xm1JU</name>
   <tag></tag>
   <elementGuidId>3990bdfc-d05e-4df4-a720-5740d7683e6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img._2xm1JU</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>verify</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2aa40a08-1505-4ef9-9537-4dad0b646615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>a6d32d24-c1d2-4ae1-805f-79c1f6b950f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/flipkart-plus_8d85f4.png</value>
      <webElementGuid>c7b140d4-b30b-46ff-9de8-fae1e7fd7b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Flipkart</value>
      <webElementGuid>8347b6c5-2d78-47c8-b5bf-44ecb39f1d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Flipkart</value>
      <webElementGuid>94efb8aa-dfb7-4f6f-90c6-5bbe4b75e377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_2xm1JU</value>
      <webElementGuid>ab636de3-fa91-4a3a-81cd-5dd84fe68cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_1kfTjk&quot;]/div[@class=&quot;_1rH5Jn&quot;]/div[@class=&quot;_2Xfa2_&quot;]/div[@class=&quot;_3_C9Hx&quot;]/div[@class=&quot;_3qX0zy&quot;]/a[1]/img[@class=&quot;_2xm1JU&quot;]</value>
      <webElementGuid>a97bdc33-573a-4e5c-a5fe-1cc9196e03b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/div[2]/div/div/a/img</value>
      <webElementGuid>4f4b2099-0509-4571-abfd-348999fdfacd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Flipkart']</value>
      <webElementGuid>ad1f81cf-eda1-421b-b3f7-e0ebc9b95c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>642a68c2-dd58-4039-883b-4dd8505060e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/flipkart-plus_8d85f4.png' and @alt = 'Flipkart' and @title = 'Flipkart']</value>
      <webElementGuid>a7f1d0b0-792d-4e4d-80c9-679a649caf2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
