<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Continue with email</name>
   <tag></tag>
   <elementGuidId>6adbeab2-9da3-4d2b-bca9-c8ba42609cf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.method_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_signin_with_email_id']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>97eed068-a07b-427a-9cf2-f2e15736c217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>method_title</value>
      <webElementGuid>eeec2eb6-df51-4abd-9b4a-910143ddb3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue with email</value>
      <webElementGuid>51ae4faf-cbcc-4147-a551-d9e5ab02beee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_signin_with_email_id&quot;)/div[@class=&quot;method_item&quot;]/div[@class=&quot;method_title&quot;]</value>
      <webElementGuid>eba212f2-29dd-47b8-8f00-8ce6f78794b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='btn_signin_with_email_id']/div/div[2]</value>
      <webElementGuid>7b088e28-fa45-4ea2-921b-35d57988864e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/div/div[2]</value>
      <webElementGuid>a6ff2621-bc55-4553-8b61-9bf7c955eaa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Continue with email' or . = 'Continue with email')]</value>
      <webElementGuid>b9c53fc7-2a61-4e3d-981d-21c569d3b6b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
