<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_login</name>
   <tag></tag>
   <elementGuidId>ac387169-a5c9-4db9-91de-eb615c422cd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_log_in</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_log_in']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57c26a66-1846-4f01-9dc5-3ecebf8c7bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sign_in_btn</value>
      <webElementGuid>3ec9d378-a581-43c9-8ba4-d8c872de7742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>8c2a72dc-924c-4608-8fe2-a859eb683668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a72464a1-7b69-4279-b1d9-1db1774d6633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log in</value>
      <webElementGuid>87ac7278-0bd3-4306-ac2f-dc06ba45ab0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_log_in</value>
      <webElementGuid>02430935-eae2-4315-bc41-f795b76f90e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_log_in&quot;)</value>
      <webElementGuid>44e71057-831b-4f6c-b5ae-1e7e207d808a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_log_in']</value>
      <webElementGuid>09a5b3da-2170-425e-8251-08323801f3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kc-content-wrapper']/div/div[2]/div/div/div[2]/div[2]/form/input</value>
      <webElementGuid>14b4e5e6-f80a-46fe-8ad5-f6c3d09c11e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>ff95f166-9f45-44d5-9066-f13e615c4985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'login' and @type = 'submit' and @id = 'btn_log_in']</value>
      <webElementGuid>34e3d685-e5a8-44db-8470-afe7ecca1300</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
