<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_a-button-input</name>
   <tag></tag>
   <elementGuidId>fed85104-fd52-4a24-9d23-e31cec75019b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GLUXZipUpdate > span.a-button-inner.a-declarative > input.a-button-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='submit'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3bc79d94-07b3-4b4d-bbef-a503f13213f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>786c143c-8c67-4a06-b356-b727c545d837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>de5857e4-c874-4853-a5b6-1f7733f51a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>GLUXZipUpdate-announce</value>
      <webElementGuid>bdbd4d97-7515-47de-ab80-6b5807bb1b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GLUXZipUpdate&quot;)/span[@class=&quot;a-button-inner a-declarative&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>37e7aaaf-e106-4dae-a80a-e5fab797c1c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='submit'])[4]</value>
      <webElementGuid>1eda965f-5c99-443e-bd63-97f6939f485a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='GLUXZipUpdate']/span/input</value>
      <webElementGuid>72f25e37-0505-4445-9745-6845f31fd024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/input</value>
      <webElementGuid>57be6404-ca73-48dc-9512-dd915ad49795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>5698b7e8-d8d3-42a5-9c78-92306722c2fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
