<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Our Site</name>
   <tag></tag>
   <elementGuidId>ab669a49-bc88-4cee-97f3-5620889ed562</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navbardrop</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navbardrop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>160faa11-2e1e-481e-ba99-b7b3a7e1e001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>47737123-f98a-4ed2-9ec4-7858c6426586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle</value>
      <webElementGuid>fa7f6143-8a3f-47a9-9404-495d0ab00ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navbardrop</value>
      <webElementGuid>44a4d694-b8d0-45b0-aaac-f2fd0f1ca386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>0fae1c54-0a5e-459c-a18a-5ef2779721aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Our Site</value>
      <webElementGuid>fca50c51-b9ff-4acd-b8e2-8a8f248bd296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js_active vc_desktop vc_transform vc_transform&quot;]/body[@class=&quot;home page-template-default page page-id-2609 mva7-thc-activetheme-district-theme lang-en wpb-js-composer js-comp-ver-5.4.7 vc_responsive js&quot;]/header[1]/div[@class=&quot;top-header-wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 social-content&quot;]/div[@class=&quot;ep-header-top-right&quot;]/div[@class=&quot;dropdown dmenu site-menu&quot;]/a[@id=&quot;navbardrop&quot;]</value>
      <webElementGuid>1cd81eda-e1d0-409d-b852-50a40cf9549d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='navbardrop']</value>
      <webElementGuid>a258a326-57ff-4b63-8120-c02f0e491616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Our Site')]</value>
      <webElementGuid>e76328df-7c99-4db8-9bac-f1f60d09992f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>24803b9c-2dac-447f-bcdb-1e8f0d023498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>3ac23c8b-424f-410e-8f17-7945186628aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'navbardrop' and (text() = 'Our Site' or . = 'Our Site')]</value>
      <webElementGuid>c03a474c-5733-4605-904a-09c0d39f06e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
