<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_scroll-down__chevron-down is-en-txt</name>
   <tag></tag>
   <elementGuidId>a86eece9-7b45-4884-bf58-c8613dd9aa4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.scroll-down__chevron-down.is-en-txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='scrollDown']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0255066b-bc9c-4be2-9098-a8e75bfc0f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>scroll-down__chevron-down is-en-txt</value>
      <webElementGuid>64c81e60-9c55-47c6-8b90-16ce36f0a785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollDown&quot;)/i[@class=&quot;scroll-down__chevron-down is-en-txt&quot;]</value>
      <webElementGuid>7290f4c4-e467-4a4a-b7ea-faca84426195</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='scrollDown']/i</value>
      <webElementGuid>ffcbe874-b49a-4c02-b0b8-7a91d8800b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>46b2279d-6727-4528-9584-be2d3c7a327c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
