<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Exhibitions</name>
   <tag></tag>
   <elementGuidId>caef5865-e5f0-4cfa-9e45-e868ff8766a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(4) > a > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='theme-header']/div/div/div[3]/div/ul/li[2]/div[2]/div/ul/li[4]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fd87afa2-7314-4f22-b680-3c95a987d380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Exhibitions</value>
      <webElementGuid>c834dc1f-8e08-4e09-991d-52e0cc7d6eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;theme-header&quot;)/div[@class=&quot;header&quot;]/div[@class=&quot;header--wrapper max-container&quot;]/div[@class=&quot;menu-wrapper&quot;]/div[@class=&quot;main-menu&quot;]/ul[@class=&quot;main-menu-list&quot;]/li[@class=&quot;list-item art-dropdown&quot;]/div[@class=&quot;mega-menu is--open&quot;]/div[@class=&quot;mega-menu-wrapper&quot;]/ul[@class=&quot;mega-menu-list&quot;]/li[4]/a[1]/span[1]</value>
      <webElementGuid>3f770d86-c266-4c04-bb82-8d3c80b94ae7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='theme-header']/div/div/div[3]/div/ul/li[2]/div[2]/div/ul/li[4]/a/span</value>
      <webElementGuid>90588781-97b3-464f-bcc9-172f5e48fa3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/span</value>
      <webElementGuid>3de05c58-f00a-4bcf-a4bd-68d76f736e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Exhibitions' or . = 'Exhibitions')]</value>
      <webElementGuid>97217e0d-48f3-4fae-be2e-1dc2e02206fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
