<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MuiBox-root jss176 jss175 arrowBtn</name>
   <tag></tag>
   <elementGuidId>cba1b78b-249d-405e-8ca3-e9df0f152b65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.jss176.jss175.arrowBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div/div[4]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>563348ae-3d90-4e59-a561-66754be02e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root jss176 jss175 arrowBtn</value>
      <webElementGuid>2e557dcb-a5d1-4147-a905-e341f0926ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>classes</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>b865aa58-98db-42b1-980c-492db4ab3150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;jss7&quot;]/div[@class=&quot;main-comp comp-0&quot;]/div[@class=&quot;jss125&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-root scrollBtnSection&quot;]/div[@class=&quot;scrollBtn&quot;]/div[@class=&quot;MuiBox-root jss176 jss175 arrowBtn&quot;]</value>
      <webElementGuid>b277f32b-200f-41b9-9e03-ea9d08c2bd8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div[4]/div/div</value>
      <webElementGuid>254eb449-1e27-4a2e-a518-429d0bc8ab5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[4]/div/div</value>
      <webElementGuid>9c85b421-a516-413d-8008-0a0c58998235</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
