<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_scroll-down__chevron-down is-en-txt</name>
   <tag></tag>
   <elementGuidId>098c9f10-003b-477a-8458-e912f60e2055</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.scroll-down__chevron-down.is-en-txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='scrollDown']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5b0fcb21-2499-41d9-8ec7-b7eab3f8e664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>scroll-down__chevron-down is-en-txt</value>
      <webElementGuid>5eea4f44-1824-4c53-acf0-7db4bf4ad290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollDown&quot;)/i[@class=&quot;scroll-down__chevron-down is-en-txt&quot;]</value>
      <webElementGuid>e3689c1d-a3e1-4b81-8e93-9a69f7ad8b90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='scrollDown']/i</value>
      <webElementGuid>3037c1ec-d3b5-4749-9656-722057276ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>41bdf3bb-dd14-4917-8faa-c0f682d400ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
