<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email</name>
   <tag></tag>
   <elementGuidId>ecfcbd7a-90c8-43ac-956b-909b98f33e9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89e10808-fb5b-4790-934a-d13354839ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>504c0ce0-c0fb-4153-8ca2-24c8481eda13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>da31fbc7-5ec9-43a0-85b3-692f271845b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your work email address</value>
      <webElementGuid>f8b28ca2-d4d5-4789-bf9a-a48a3582ca57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>394cad21-32c3-4ec5-b17f-af064f279b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>current-email</value>
      <webElementGuid>87708b27-17a3-4cae-a3aa-0a2353e33d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bs-input-md bs-input</value>
      <webElementGuid>96928578-9bec-470a-9c22-712a5a707bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>k</value>
      <webElementGuid>c385ef8e-f267-4a87-813b-d7e8221c30c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;auth&quot;]/div[@class=&quot;auth-wrapper&quot;]/div[@class=&quot;auth-container&quot;]/form[@class=&quot;auth-container--form&quot;]/div[@class=&quot;auth-form-row&quot;]/div[@class=&quot;auth-form-input email&quot;]/div[@class=&quot;bs-input-container input--container&quot;]/span[@class=&quot;bs-input-affix-wrapper bs-input-affix-wrapper-md input-&quot;]/input[@class=&quot;bs-input-md bs-input&quot;]</value>
      <webElementGuid>68d60213-6d1b-46f8-960c-c7a78470f7e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>183ffbb4-ef86-4f9c-80ef-fcf457b3ddb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[9]/div[2]/div/form/div/div/div/span/input</value>
      <webElementGuid>6e479a47-2881-491a-9804-2c44a9d05208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9aabf592-2bad-4197-bfdd-518d90dc8ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email' and @type = 'email' and @placeholder = 'Enter your work email address']</value>
      <webElementGuid>deeae316-738d-42fa-926d-6fe09f1214ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
