<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Courses</name>
   <tag></tag>
   <elementGuidId>f154b1f3-2347-4394-92a2-46986dd63e14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-3727 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-3727']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c4ecf9c2-bcf1-407f-bdd7-335567b277aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://academy.katalon.com/courses/</value>
      <webElementGuid>827b0c72-02e3-4179-9f3a-401b17f50321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Courses</value>
      <webElementGuid>2f3cf070-1c9b-445e-9e0d-5ac51345b624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-main-menu&quot;)/li[@id=&quot;menu-item-3727&quot;]/a[1]</value>
      <webElementGuid>487c16d3-3b93-4b82-8bf4-11ce1243b2e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-3727']/a</value>
      <webElementGuid>97787575-cff6-4986-baec-006be85313de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Courses')]</value>
      <webElementGuid>d25c76d1-bf60-4905-877d-d6644d87e98d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://academy.katalon.com/courses/')]</value>
      <webElementGuid>a4a7c3ce-bd6c-444c-811f-3113f8165814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>ab75aa15-5c03-4aea-b7f4-a49b0b05d909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://academy.katalon.com/courses/' and (text() = 'Courses' or . = 'Courses')]</value>
      <webElementGuid>8cbd728a-aeba-4cae-a725-8db6b8d2f806</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
