<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ytp-fullscreen-button ytp-button</name>
   <tag></tag>
   <elementGuidId>cb0bafde-86bc-4425-955a-e587c901677c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ytp-fullscreen-button.ytp-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='movie_player']/div[29]/div[2]/div[2]/button[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>48a52d3e-2a53-4658-a62e-9f1d9356db1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ytp-fullscreen-button ytp-button</value>
      <webElementGuid>3a6884f5-9b7c-457e-b5e1-dd8b58fbc791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-keyshortcuts</name>
      <type>Main</type>
      <value>f</value>
      <webElementGuid>e9b55b88-b375-4b63-aea9-ee2ada1c81c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-priority</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>ae763c19-935d-434b-90d6-33b2d1320eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title-no-tooltip</name>
      <type>Main</type>
      <value>Full screen</value>
      <webElementGuid>fce31c2b-6a16-4ee0-8827-b072c92f3844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Full screen keyboard shortcut f</value>
      <webElementGuid>01f20b00-1f86-4e3d-9c1c-2544f17a09d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;movie_player&quot;)/div[@class=&quot;ytp-chrome-bottom&quot;]/div[@class=&quot;ytp-chrome-controls&quot;]/div[@class=&quot;ytp-right-controls&quot;]/button[@class=&quot;ytp-fullscreen-button ytp-button&quot;]</value>
      <webElementGuid>2781ec10-917e-4d2d-83f0-6690c84d39e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='movie_player']/div[29]/div[2]/div[2]/button[9]</value>
      <webElementGuid>026c40eb-612b-4a02-a114-d7bfee85172b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[9]</value>
      <webElementGuid>c3ed818a-e204-41a0-a9d8-b414161b2939</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
