<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Skip</name>
   <tag></tag>
   <elementGuidId>e6e01d79-f813-4937-951c-9231d9e0b86f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ad-text:6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>93e5cc21-4fe3-4244-97ba-b2d969434852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ytp-ad-text ytp-ad-skip-button-text-centered ytp-ad-skip-button-text</value>
      <webElementGuid>0dc6893f-2dc8-4faa-9ba6-df3d19ec3ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ad-text:6</value>
      <webElementGuid>eca60059-8454-4d13-b15b-2e99a64650b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Skip</value>
      <webElementGuid>d0bd6e43-6593-49dc-8148-2a6a1f7b702e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ad-text:6&quot;)</value>
      <webElementGuid>09df3205-b67d-4eb2-9a3d-7164abb806f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ad-text:6']</value>
      <webElementGuid>11fc7878-91c6-407d-8b73-c748205ef67f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='skip-button:5']/span/button/div</value>
      <webElementGuid>ac1328ea-bdbb-438e-ace8-5f5816bf0857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button/div</value>
      <webElementGuid>d1322a93-314f-4609-978c-f77539704008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ad-text:6' and (text() = 'Skip' or . = 'Skip')]</value>
      <webElementGuid>206a1265-d3f9-49e0-8097-4b2ca16b213b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
