<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>e6964ee8-684e-4f53-aa7f-dff8a14e63c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(6)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SIvCob']/a[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7ba52161-99b3-4651-9450-a4cfd09dea17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.com/setprefs?sig=0_jpHRrLtN7vI5bUOCI_44BkMU7Q0%3D&amp;hl=gu&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwiztIn29_yDAxX6avUHHdfdB9UQ2ZgBCBk</value>
      <webElementGuid>49c59dfa-c5a0-4ee2-851a-811b00493ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ગુજરાતી</value>
      <webElementGuid>49cbb7eb-6dc4-4bb5-963e-150b17b4aaa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SIvCob&quot;)/a[6]</value>
      <webElementGuid>d33d5a0b-b481-49c2-9fe2-5dd0c66dab1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SIvCob']/a[6]</value>
      <webElementGuid>8c5bde39-43e9-4536-96c6-caa4906e898f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ગુજરાતી')]</value>
      <webElementGuid>f161fbe7-623b-4b30-a286-28e2f3803d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.com/setprefs?sig=0_jpHRrLtN7vI5bUOCI_44BkMU7Q0%3D&amp;hl=gu&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwiztIn29_yDAxX6avUHHdfdB9UQ2ZgBCBk')]</value>
      <webElementGuid>7729d29b-84fc-4d41-8729-216329df9caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]</value>
      <webElementGuid>3969ffbe-0f0c-43b7-a155-c53fdad9c6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.com/setprefs?sig=0_jpHRrLtN7vI5bUOCI_44BkMU7Q0%3D&amp;hl=gu&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwiztIn29_yDAxX6avUHHdfdB9UQ2ZgBCBk' and (text() = 'ગુજરાતી' or . = 'ગુજરાતી')]</value>
      <webElementGuid>bdcd2bb7-474e-48d0-aab9-1f7ad9bb5fff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
