<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_upload a file</name>
   <tag></tag>
   <elementGuidId>e671e3b4-1084-4de4-980f-a5b4dc96a40a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.DV7the</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ow16']/div[3]/c-wiz/div[2]/div/div[3]/div[2]/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e8b0c755-17f0-45b0-bb7d-93c5bbbef9b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ved</name>
      <type>Main</type>
      <value>0CA0QmN4IahcKEwj40fSG-fyDAxUAAAAAHQAAAAAQAg</value>
      <webElementGuid>f54a7c98-1610-479d-81db-146de2a19fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>35cceabf-9b9a-4c1c-88c5-de95d19322b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cbfef740-38ee-4a2e-8540-18820141c10c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>tAPGc</value>
      <webElementGuid>34ae3346-a05b-4354-916a-b0ae8c0c055e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DV7the</value>
      <webElementGuid>97766ac8-9154-418c-ae1d-8ee5206811da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>D0HE7</value>
      <webElementGuid>8b74b98b-3b7f-463e-ab7c-b35a298dd619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>upload a file  </value>
      <webElementGuid>8f6136bf-3a07-497f-9d8c-055e80167b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ow16&quot;)/div[@class=&quot;M8H8pb&quot;]/c-wiz[@class=&quot;Aye1k&quot;]/div[@class=&quot;ea0Lbe&quot;]/div[@class=&quot;KoWHpd&quot;]/div[@class=&quot;gIYJUc&quot;]/div[@class=&quot;f6GA0&quot;]/div[@class=&quot;BH9rn&quot;]/div[@class=&quot;ZeVBtc&quot;]/span[@class=&quot;DV7the&quot;]</value>
      <webElementGuid>e4415a8f-3f73-4c64-b287-b39e7701fe74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ow16']/div[3]/c-wiz/div[2]/div/div[3]/div[2]/div/div[2]/span</value>
      <webElementGuid>0f1bc03c-cdd4-488f-a0f9-f3dbbb72d81d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/span</value>
      <webElementGuid>1bd446de-59cf-4ace-95aa-c2868c650b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'upload a file  ' or . = 'upload a file  ')]</value>
      <webElementGuid>412b1d85-df73-43a1-b1cd-3c5173e9f303</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
