<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Gdd5U</name>
   <tag></tag>
   <elementGuidId>d57cb3eb-a152-4da0-8629-c40dd22ff655</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.Gdd5U</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>7b7fee4a-f72e-4d0e-a08d-6c1219455cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Gdd5U</value>
      <webElementGuid>e4e85ac0-959b-4293-a4ed-63424b554254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fa50ae8f-dd11-4694-b743-8a6080da8085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 192 192</value>
      <webElementGuid>d58717d9-2f5d-4cdc-859b-93d307a797e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>fd7f44da-5931-4d08-a827-5c946c8ea25e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;L3eUgb&quot;]/div[@class=&quot;o3j99 ikrT4e om7nvf&quot;]/form[1]/div[1]/div[@class=&quot;A8SBwf&quot;]/div[@class=&quot;RNNXgb&quot;]/div[@class=&quot;SDkEP&quot;]/div[@class=&quot;dRYYxd&quot;]/div[@class=&quot;nDcEnd&quot;]/svg[@class=&quot;Gdd5U&quot;]</value>
      <webElementGuid>6eb023ea-d0b8-45af-a257-5348b45b3ac0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
