<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_client-c-logo</name>
   <tag></tag>
   <elementGuidId>a69725e8-6839-46a2-a259-4772d14f253b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://assets-global.website-files.com/64feb7c4af2e29e2463d3f48/652e2731844d3645bb40eebc_image%20287.jpg')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d03128e9-e3fb-406e-b6ce-65ea3495c547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets-global.website-files.com/64feb7c4af2e29e2463d3f48/652e2731844d3645bb40eebc_image%20287.jpg</value>
      <webElementGuid>719c1b35-5ba0-4274-aede-35d1bad8a9f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>client-c-logo</value>
      <webElementGuid>3b582870-4358-4eda-83f4-8c89742e477e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;w-mod-js wf-montserrat-n1-active wf-montserrat-i1-active wf-montserrat-n2-active wf-montserrat-i2-active wf-montserrat-n3-active wf-montserrat-i3-active wf-montserrat-n4-active wf-montserrat-i4-active wf-montserrat-n5-active wf-montserrat-i5-active wf-montserrat-n6-active wf-montserrat-i6-active wf-montserrat-n7-active wf-montserrat-i7-active wf-montserrat-n8-active wf-montserrat-i8-active wf-montserrat-n9-active wf-montserrat-i9-active wf-archivo-n3-active wf-archivo-n4-active wf-archivo-n5-active wf-archivo-n6-active wf-active w-mod-ix wf-instrumentsans-n4-active&quot;]/body[@class=&quot;contact-body loader-init loader-hide loaded&quot;]/section[@class=&quot;contact-page-form section-py&quot;]/div[@class=&quot;container-x&quot;]/div[@class=&quot;contact-form-row&quot;]/div[@class=&quot;contact-form-col1&quot;]/div[@class=&quot;contact-client-logos-c&quot;]/div[@class=&quot;w-layout-hflex contact-client-logos&quot;]/img[@class=&quot;client-c-logo&quot;]</value>
      <webElementGuid>a667869f-682c-4894-b799-28f60d1efe78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://assets-global.website-files.com/64feb7c4af2e29e2463d3f48/652e2731844d3645bb40eebc_image%20287.jpg')]</value>
      <webElementGuid>f619ad36-17d6-4ad7-b665-72ff9ba5f497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[7]</value>
      <webElementGuid>41fc41da-34d4-4f01-9469-cae593281e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets-global.website-files.com/64feb7c4af2e29e2463d3f48/652e2731844d3645bb40eebc_image%20287.jpg']</value>
      <webElementGuid>d2de91d4-b67a-4b66-8012-aed2bd9aebea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
