<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_KS</name>
   <tag></tag>
   <elementGuidId>3a3f9203-b0f4-49ef-bd1d-adf6356568a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.tutor-text-avatar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='masthead']/div/div/div/div/div[4]/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ece472a2-e506-4ea1-b03f-ea70cda1aca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tutor-text-avatar</value>
      <webElementGuid>71e31fb5-92c9-481f-b4b3-41da19f042c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KS</value>
      <webElementGuid>c9624d6a-6186-4553-a406-56bc34496f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/header[@id=&quot;masthead&quot;]/div[@class=&quot;container-fluid kata-container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;primary-menu&quot;]/div[@class=&quot;row align-items-center justify-content-between&quot;]/div[@class=&quot;col-md-auto  col-auto header-login-cart-wrap&quot;]/div[@class=&quot;skillate-header-login d-inline-block&quot;]/div[@class=&quot;header_profile_menu&quot;]/div[@class=&quot;skillate_header_profile_photo&quot;]/span[@class=&quot;tutor-text-avatar&quot;]</value>
      <webElementGuid>24599992-0540-4df9-961c-3a9b1e50e9c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='masthead']/div/div/div/div/div[4]/div/div/div/span</value>
      <webElementGuid>d440a8c8-da6d-4e6f-9524-4bf6cf0aab1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>19c70d75-57bb-4b6a-841a-1c1a4ab57844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'KS' or . = 'KS')]</value>
      <webElementGuid>e1e146e0-d75a-4cfe-a7f2-d28f1f4f0b65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
