<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Success Stories</name>
   <tag></tag>
   <elementGuidId>ec11f3d9-000f-4e81-87bb-fd9ed099691f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page']/footer/div/div/div[2]/div/div[4]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed8d4cdb-60d3-41c5-ad7d-9cf85f78ef2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://katalon.com/case-studies/</value>
      <webElementGuid>607e53c3-a7e4-447d-add3-701b71a63f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>https://katalon.com/case-studies/</value>
      <webElementGuid>84cfabf1-0e2b-44dc-92b2-54645b8b9a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block text-sm pb-2 text-black hover:text-lilac-600</value>
      <webElementGuid>04608d44-0efb-4998-8347-ef026cb42e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Success Stories                                        </value>
      <webElementGuid>dc933c3e-2f90-4a72-87c4-cf10cc380392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/footer[1]/div[@class=&quot;tw-newbrand22&quot;]/div[@class=&quot;container font-sans mx-auto px-4 x:px-0 md:flex&quot;]/div[@class=&quot;flex-1&quot;]/div[@class=&quot;grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2&quot;]/div[4]/ul[1]/li[@class=&quot;p-0&quot;]/a[@class=&quot;block text-sm pb-2 text-black hover:text-lilac-600&quot;]</value>
      <webElementGuid>8b0ab771-dbeb-4b25-a5e3-d1f46ffdf377</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/footer/div/div/div[2]/div/div[4]/ul/li[3]/a</value>
      <webElementGuid>0cd3a7e5-0cd3-4b75-9cfc-a739d56f76fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Success Stories')])[4]</value>
      <webElementGuid>b93fe154-93fd-4f82-a3f5-2899f71fbba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://katalon.com/case-studies/')]</value>
      <webElementGuid>c16dacfe-5d9c-40b6-a956-97d913ddaa6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[3]/a</value>
      <webElementGuid>05f43724-90a4-4663-a018-8f870f1b6ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://katalon.com/case-studies/' and (text() = '
                                            Success Stories                                        ' or . = '
                                            Success Stories                                        ')]</value>
      <webElementGuid>2f77e1ca-2226-4920-9e9f-1154e7f5858d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
