<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__deals-hero-shoveler_style_image__39grG</name>
   <tag></tag>
   <elementGuidId>2772ec70-1abd-4ed4-98bb-a64172038de7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='anonCarousel1']/ol/li[2]/div/div/div/div/a/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>68e13f2c-313e-4bb1-b96d-36f5c8ea4721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Redmi 13C 5G (4/128)</value>
      <webElementGuid>f12928a9-b487-415f-82e7-cf3595a8f10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/41QbhV8nEnL._AC_UF420%2C420_FMjpg_.jpg</value>
      <webElementGuid>3580c8d5-4e4a-4af8-bd8d-3063318cce64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_deals-hero-shoveler_style_image__39grG</value>
      <webElementGuid>c9305b95-97c5-4007-a3de-021cf0f86e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anonCarousel1&quot;)/ol[@class=&quot;a-carousel&quot;]/li[@class=&quot;a-carousel-card _deals-hero-shoveler_style_elementWrapper__kN6lv&quot;]/div[@class=&quot;_deals-hero-shoveler_style_element__TNuHE&quot;]/div[@class=&quot;_deals-hero-shoveler_style_cardBody__uIG6x&quot;]/div[@class=&quot;a-row _deals-hero-shoveler_style_innerCardBody__2PiR0&quot;]/div[@class=&quot;_deals-hero-shoveler_style_imageBackground__1W2y-&quot;]/a[@class=&quot;a-link-normal&quot;]/div[@class=&quot;a-section a-spacing-top-small&quot;]/div[@class=&quot;a-image-container a-dynamic-image-container aok-align-center-horizontally&quot;]/img[@class=&quot;_deals-hero-shoveler_style_image__39grG&quot;]</value>
      <webElementGuid>ed2ddf1e-f8ce-4c8d-9277-a8cb3e3ba836</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='anonCarousel1']/ol/li[2]/div/div/div/div/a/div/div/img</value>
      <webElementGuid>213c7bf8-f577-4da7-9dfd-797bcfd01bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Redmi 13C 5G (4/128)']</value>
      <webElementGuid>03a6bed9-a0f5-4c49-ae90-22f3161399e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/div/a/div/div/img</value>
      <webElementGuid>045f61ab-dce3-4771-a2b9-a3bfde3a4365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Redmi 13C 5G (4/128)' and @src = 'https://m.media-amazon.com/images/I/41QbhV8nEnL._AC_UF420%2C420_FMjpg_.jpg']</value>
      <webElementGuid>c554b478-e383-40d0-ba1a-6eb4568f38a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
