<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_login</name>
   <tag></tag>
   <elementGuidId>3d2d2ae7-3e84-434b-95cc-541128243188</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_log_in</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_log_in']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd26ce47-7b84-4fbe-9967-163000e1064d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sign_in_btn</value>
      <webElementGuid>1b98c7a6-95cb-4f55-a883-6e77a9de0cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>59992a39-dc08-4aa2-8a92-bde100ce988d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>745f725d-bccd-4a2b-81ce-54bd77af4377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log in</value>
      <webElementGuid>2198c991-a32a-404d-94e3-d0627dbd40cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_log_in</value>
      <webElementGuid>4e24d8bd-356e-4f33-b713-1e6b40e834cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_log_in&quot;)</value>
      <webElementGuid>7e4ff513-7055-440a-b706-1447f2014231</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_log_in']</value>
      <webElementGuid>dc9f51ea-a2f4-4d9a-8357-88f11c82cb3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kc-content-wrapper']/div/div[2]/div/div/div[2]/div[2]/form/input</value>
      <webElementGuid>c76dfccd-f45f-4538-83aa-7433e3e69988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>2a2e8abd-a702-4433-bb0d-3eb406f56923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'login' and @type = 'submit' and @id = 'btn_log_in']</value>
      <webElementGuid>3f1ad65b-3a47-41f6-8901-3ff2a4c9a3db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
