<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PayZapp</name>
   <tag></tag>
   <elementGuidId>91e86a5d-2baa-4f82-910b-258177aea43b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[2]/div[13]/div[4]/div/div/div/div[3]/div/div/div/div[3]/div/div/div/div/div/div/div/div[2]/div/div/h3/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9b8b7c26-df17-4b73-9387-59583f8e7917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://v.hdfcbank.com/payzapp/index.html</value>
      <webElementGuid>97003e30-35ba-4fdb-acc3-ffa5451339f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>420f8225-21f6-43d0-9467-edece36d2126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PayZapp </value>
      <webElementGuid>b2a186cf-5463-4687-867d-9be4e4ce9c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;lp-page-children bp-area --area&quot;]/div[@class=&quot;bp-container bp-ui-dragRoot bp-manageableArea --area bp-area&quot;]/div[@class=&quot;bp-container c-template-hdfc-middle-section&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;bp-area c-template-hdfc-middle-section--area&quot;]/div[@class=&quot;bp-container c-template-hdfc-portal-8-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;bp-area s-hdfc-app--area col-lg-8 col-sm-8&quot;]/div[@class=&quot;bp-widget bp-ui-dragRoot&quot;]/div[@class=&quot;bp-widget-body&quot;]/div[1]/div[@class=&quot;bd-structured-content-widget&quot;]/div[@class=&quot;bp-g-include&quot;]/div[@class=&quot;carousel-three-slides-superparent&quot;]/div[@class=&quot;carousel-three-slides-parent slick-initialized slick-slider&quot;]/div[@class=&quot;slick-list draggable&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;carousel-three-slides-div first-col slick-slide slick-active&quot;]/div[@class=&quot;slides-div&quot;]/div[@class=&quot;row-style&quot;]/h3[@class=&quot;font-style&quot;]/a[1]</value>
      <webElementGuid>74b549a2-7afd-42c3-a3fc-a181bf2cc276</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/div[13]/div[4]/div/div/div/div[3]/div/div/div/div[3]/div/div/div/div/div/div/div/div[2]/div/div/h3/a</value>
      <webElementGuid>b70c8bb2-1aa3-4299-a4dd-e295cc030152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PayZapp')]</value>
      <webElementGuid>588fd85b-556b-4c7c-89b6-15f55419ea09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://v.hdfcbank.com/payzapp/index.html')])[4]</value>
      <webElementGuid>214d96e2-3dfd-4094-9b47-6d2e26a69df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/h3/a</value>
      <webElementGuid>d6686cd3-8737-47c1-a3c4-87f942a7ec50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://v.hdfcbank.com/payzapp/index.html' and (text() = 'PayZapp ' or . = 'PayZapp ')]</value>
      <webElementGuid>1678878e-98bf-4a15-88fa-364d2a65f162</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
