<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_scroll-down__chevron-down is-en-txt</name>
   <tag></tag>
   <elementGuidId>19718ae9-6e65-4871-9259-d75b3968b3b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.scroll-down__chevron-down.is-en-txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='scrollDown']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c0a29749-cff5-41d4-ade8-223e3de5a3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>scroll-down__chevron-down is-en-txt</value>
      <webElementGuid>f5192696-9383-48b3-a546-69e26679b2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollDown&quot;)/i[@class=&quot;scroll-down__chevron-down is-en-txt&quot;]</value>
      <webElementGuid>72032b08-4e9f-463f-beea-19328df0affa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='scrollDown']/i</value>
      <webElementGuid>6fa01bc9-d96f-42b8-916d-ee856afdacdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>eed8a949-26ae-4225-bc6c-2f2d66ee8bb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
