<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>5cc7c432-d319-41c3-93ce-6ba1610abcb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.lang</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='theme-header']/div/div/div[3]/div[2]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aa39102d-9e9c-4357-b7be-3809cee79045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>06f12b49-93ba-4518-9c4e-029ec835de04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>العربية</value>
      <webElementGuid>e9924388-3e60-4025-9699-11034c56444e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;theme-header&quot;)/div[@class=&quot;header&quot;]/div[@class=&quot;header--wrapper max-container&quot;]/div[@class=&quot;menu-wrapper&quot;]/div[@class=&quot;lang-wrapper&quot;]/ul[1]/li[@class=&quot;li-lang&quot;]/a[@class=&quot;lang&quot;]</value>
      <webElementGuid>316037c7-74f6-414c-a26c-1f1f34a12755</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='theme-header']/div/div/div[3]/div[2]/ul/li[2]/a</value>
      <webElementGuid>65fd1138-7816-42d8-8d9b-6cd21ab3dd1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'العربية')]</value>
      <webElementGuid>511ce155-2349-4aca-92f7-a0159507e895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a</value>
      <webElementGuid>ac43aef9-a53f-4e1e-9eb6-69e42e4c5b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'العربية' or . = 'العربية')]</value>
      <webElementGuid>05851482-609e-416f-9d57-77f5a4877da3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
