<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_scroll-down__chevron-down is-en-txt</name>
   <tag></tag>
   <elementGuidId>1714d4cc-4321-4368-ab02-b53b74d5bfdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.scroll-down__chevron-down.is-en-txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='scrollDown']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b37648b4-3c23-4278-9479-6ab6dcbf9d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>scroll-down__chevron-down is-en-txt</value>
      <webElementGuid>2073669c-67ab-4814-96f9-ead015d78e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollDown&quot;)/i[@class=&quot;scroll-down__chevron-down is-en-txt&quot;]</value>
      <webElementGuid>3eafa51f-89c8-4159-a98e-e6fa2907147b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='scrollDown']/i</value>
      <webElementGuid>70340590-b0a2-4e34-81d2-764f93eefa90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>45adf153-e518-424a-8862-eca876377a8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
