<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Trending</name>
   <tag></tag>
   <elementGuidId>a9ed86c1-a880-4183-b954-39063e0a54d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.yt-core-attributed-string.yt-core-attributed-string--white-space-pre-wrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-header']/yt-page-header-renderer/yt-page-header-view-model/div/div/div/yt-dynamic-text-view-model/h1/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ccc04e86-4c60-44da-bb3c-4d8290b63bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yt-core-attributed-string yt-core-attributed-string--white-space-pre-wrap</value>
      <webElementGuid>d9cdec50-242e-40d2-9f93-aa259047de14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>e59eda76-bd0c-4dbf-9596-76baf7dd353b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>26594b23-6b36-4b6f-bac9-a03d7daa80cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Trending</value>
      <webElementGuid>422bd06d-3fa5-4032-b622-2341822ba4a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/tp-yt-app-header[@id=&quot;header&quot;]/div[@id=&quot;contentContainer&quot;]/div[@id=&quot;page-header-container&quot;]/div[@id=&quot;page-header&quot;]/yt-page-header-renderer[@class=&quot;page-header-renderer-wiz style-scope ytd-tabbed-page-header&quot;]/yt-page-header-view-model[@class=&quot;page-header-view-model-wiz page-header-view-model-wiz--no-padding&quot;]/div[@class=&quot;page-header-view-model-wiz__page-header-content&quot;]/div[@class=&quot;page-header-view-model-wiz__page-header-headline&quot;]/div[@class=&quot;page-header-view-model-wiz__page-header-headline-info&quot;]/yt-dynamic-text-view-model[@class=&quot;dynamic-text-view-model-wiz page-header-view-model-wiz__page-header-title page-header-view-model-wiz__page-header-title--page-header-title-large&quot;]/h1[@class=&quot;dynamic-text-view-model-wiz__h1&quot;]/span[@class=&quot;yt-core-attributed-string yt-core-attributed-string--white-space-pre-wrap&quot;]</value>
      <webElementGuid>06ae1aa6-5467-47ac-b44e-2fc308da4657</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-header']/yt-page-header-renderer/yt-page-header-view-model/div/div/div/yt-dynamic-text-view-model/h1/span</value>
      <webElementGuid>c2c77b2c-c90e-49df-ad2e-d7f3f8484ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>4c7779af-acc0-4615-a386-46721bc04b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Trending' or . = 'Trending')]</value>
      <webElementGuid>521e729c-650e-4849-b6da-d55e54a495fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
