<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yt-formatted-string_Gaming</name>
   <tag></tag>
   <elementGuidId>d9dd5e92-82cb-4dd6-b70d-45aa5edf7190</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//yt-formatted-string[@id='text'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>yt-formatted-string</value>
      <webElementGuid>a8deacff-88e9-4c53-ae1d-d6436bc30b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>40d0f955-78c8-4f29-9b88-bf807b1e146f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-scope yt-chip-cloud-chip-renderer</value>
      <webElementGuid>7ce0b919-6079-41cc-b7f2-d1236462f2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Gaming</value>
      <webElementGuid>fd8c0c81-c14a-42aa-bbc3-9311df0e857b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gaming</value>
      <webElementGuid>f4df71b4-33e0-4419-bca6-5c87b93317d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chips&quot;)/yt-chip-cloud-chip-renderer[@class=&quot;style-scope ytd-feed-filter-chip-bar-renderer&quot;]/yt-formatted-string[@id=&quot;text&quot;]</value>
      <webElementGuid>32ea696f-5945-4529-b67d-44f54b889888</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//yt-formatted-string[@id='text'])[6]</value>
      <webElementGuid>3c8d80af-48c8-4cdd-b2e0-24d8d5bc2105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//iron-selector[@id='chips']/yt-chip-cloud-chip-renderer[6]/yt-formatted-string</value>
      <webElementGuid>18b1412a-25cf-40bf-89e4-8de19025f706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//yt-chip-cloud-chip-renderer[6]/yt-formatted-string</value>
      <webElementGuid>78299413-eab6-4aa4-9d3a-66181fbd40ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//yt-formatted-string[@id = 'text' and @title = 'Gaming' and (text() = 'Gaming' or . = 'Gaming')]</value>
      <webElementGuid>f2263537-a744-4ba5-9b70-e4813da7facf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
