<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Save</name>
   <tag></tag>
   <elementGuidId>81b953dd-1393-4448-bdb3-669dcd9689e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ktl-editname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ktl-editname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>da1e792c-7b30-4226-bff5-d699f444341e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>startChangeName()</value>
      <webElementGuid>7e20726b-f648-4de1-b459-e9d7915aa210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ktl-editname</value>
      <webElementGuid>6e4b7344-7966-47f3-8229-59a05b2bc8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>a3c636be-15b5-4ca2-9dfb-e40b6a20e05a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ktl-editname&quot;)</value>
      <webElementGuid>4cd6098e-9299-4671-a713-3b68be3952a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ktl-editname']</value>
      <webElementGuid>1c2ad8aa-d64c-47f1-85e1-460d9e5e3af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/div[4]/div/div/div/div/div/div[2]</value>
      <webElementGuid>6a82d66c-adbc-40f1-8630-6c78d8373247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div[2]</value>
      <webElementGuid>55a67eaf-5597-45f7-b058-f7469472d4d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ktl-editname' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>cf481014-7652-4b8b-b39b-54753ad1c901</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
