<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Edit name</name>
   <tag></tag>
   <elementGuidId>ac1a6e60-e83b-4659-b588-f851fb1e69bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ktl-editname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ktl-editname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>599de4fc-f1ac-4516-9022-80a3dc640274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>startChangeName()</value>
      <webElementGuid>6d8953e9-2d47-4e55-9ec6-23090a79a4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ktl-editname</value>
      <webElementGuid>4545cd72-90aa-4e1f-9944-70c4fd2aa22b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit name</value>
      <webElementGuid>7397451d-956b-4e06-8b86-dc2eb67d3b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ktl-editname&quot;)</value>
      <webElementGuid>da98e582-f121-4d86-b0b7-b0ece9ad4b7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ktl-editname']</value>
      <webElementGuid>19d9e5cf-f3b4-434e-98cc-b07a5c02fa41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/div[4]/div/div/div/div/div/div[2]</value>
      <webElementGuid>861533a6-9bc5-4536-9af7-d6e753d309b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div[2]</value>
      <webElementGuid>21a4f96e-4928-4c2e-b2f8-82fead746cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ktl-editname' and (text() = 'Edit name' or . = 'Edit name')]</value>
      <webElementGuid>6c9b6abb-d336-4be9-95db-b1716949e0b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
