<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_username</name>
   <tag></tag>
   <elementGuidId>9ae60a4e-e0b0-44a1-a5cc-f2f5050f2cf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ip_username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ip_username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>130b482d-ec23-4957-9f52-618491ffdacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c0c9769c-9330-4761-bf26-4e7771d4ecee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.select();</value>
      <webElementGuid>82d7eb58-ba79-4e90-9f9f-168462b39975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ip_username</value>
      <webElementGuid>ff687b8c-3daf-4b83-a785-8c3a1f213104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f92f785-95db-4022-9ef2-b329fcb39279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>fce80974-b67e-4c93-ab15-845d26c8d172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Kuldipsinh Solanki</value>
      <webElementGuid>c109de97-7229-4876-a88d-d1370b91873b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ip_username&quot;)</value>
      <webElementGuid>6cfc7f59-eb37-4186-b59c-13d695d1e8f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ip_username']</value>
      <webElementGuid>fcc2bf11-e752-4b34-83e6-6a1e78812398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ip_wrapper']/input</value>
      <webElementGuid>83dce633-5b18-4c90-a013-ab918c781983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4/div/input</value>
      <webElementGuid>b76c7dd1-2572-404e-8c80-a4509be90f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ip_username' and @type = 'text' and @name = 'username']</value>
      <webElementGuid>b1c2a1f8-5cab-42f2-a0d2-af1aadae8481</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
