<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_NRI</name>
   <tag></tag>
   <elementGuidId>feef6a66-f76e-44e8-88c0-8e34ac0185db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;NRI&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@value='ext-link-nb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>13831035-15a0-40a8-a3f6-d41f086ea461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>NRI</value>
      <webElementGuid>ad473d06-81f3-424c-ab84-6f59cbe670fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/nri-banking</value>
      <webElementGuid>18d0bab9-f769-42e4-b038-7d889747f772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ext-link-nb</value>
      <webElementGuid>6a59b819-051b-4259-a97c-ccedeab099ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-linktype</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>5b9b9b25-4cbf-4834-80bd-66129af9c736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uuid</name>
      <type>Main</type>
      <value>2bb71cb8-3229-4da9-ad46-b27cea3bd048</value>
      <webElementGuid>26ee135e-b69d-4d3c-a695-b7ca4a0e0768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NRI</value>
      <webElementGuid>b02252cf-6841-4bc3-b84a-ab303d31cfa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;lp-page-children bp-area --area&quot;]/header[1]/div[@class=&quot;top-menu&quot;]/div[@class=&quot;row main-nav-container&quot;]/div[@class=&quot;main-header bp-container B-template-hdfc-header container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;bp-area B-template-hdfc-header--area col-lg-9 col-md-8 col-sm-10 col-xs-8&quot;]/div[@class=&quot;bp-widget bp-ui-dragRoot&quot;]/div[@class=&quot;bp-widget-body ng-scope&quot;]/div[@class=&quot;main-nav&quot;]/div[@class=&quot;bp-g-model&quot;]/div[@class=&quot;lp-navbar-advanced ng-scope&quot;]/div[@class=&quot;navbar navbar-inverse navbar-static-top&quot;]/div[@class=&quot;header-menu container-fluid&quot;]/div[@class=&quot;navbar-collapse&quot;]/ul[@class=&quot;nav navbar-nav lp-navbar-advanced-root normal-main-header&quot;]/li[@class=&quot;&quot;]/a[1]</value>
      <webElementGuid>42f7103a-543d-4c5e-b234-d6e3737b9add</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@value='ext-link-nb']</value>
      <webElementGuid>3edfaa7d-5cea-4a4f-8ae5-e817adacc806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/header/div/div/div/div/div[2]/div/div[3]/div/div/div/div/div/div[2]/ul/li[2]/a</value>
      <webElementGuid>ec3df0aa-1c33-43b1-917b-f33ac014d230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'NRI')]</value>
      <webElementGuid>a186fd70-d7ff-41c2-a8ef-a94a6dd81939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/nri-banking')]</value>
      <webElementGuid>a0251cdb-0821-43f6-b35c-858dbd3aaa3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[2]/ul/li[2]/a</value>
      <webElementGuid>cd888f72-64a2-4220-bb20-e4876fc3c5a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'NRI' and @href = '/nri-banking' and (text() = 'NRI' or . = 'NRI')]</value>
      <webElementGuid>aad2ba1b-f4f5-4071-ba81-91d62d332427</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
