<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Continue with email</name>
   <tag></tag>
   <elementGuidId>0c314eb5-d18f-471c-9521-2e94de1fff3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.method_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_signin_with_email_id']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ffe2ddb5-64b8-45e3-ae07-10f3a2569f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>method_title</value>
      <webElementGuid>a3b4bca2-676c-4993-b01e-dc83140f15ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue with email</value>
      <webElementGuid>f07607ba-df0a-4e17-8ec6-b6725682e9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_signin_with_email_id&quot;)/div[@class=&quot;method_item&quot;]/div[@class=&quot;method_title&quot;]</value>
      <webElementGuid>dfc26b21-ac1e-487c-b161-d82e86d75b7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='btn_signin_with_email_id']/div/div[2]</value>
      <webElementGuid>472131f5-4d8d-4616-98c1-1104f0d46454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/div/div[2]</value>
      <webElementGuid>8a1dfc5d-97a4-4156-a4f3-0bfa60c0c0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Continue with email' or . = 'Continue with email')]</value>
      <webElementGuid>357f3e99-1315-4856-8bfa-740de5896f24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
