<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sequence duplicated successfully</name>
   <tag></tag>
   <elementGuidId>39d98d36-7958-4597-bf91-78b8bbe78da6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.message-desc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[7]/div[2]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>66f01c68-de2c-4ccc-8960-890661f9fbea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>message-desc</value>
      <webElementGuid>f85b8e7c-1031-4d98-96c1-94f4aecc65ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sequence duplicated successfully</value>
      <webElementGuid>32282a62-a153-4382-8829-83ab65ed25be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bs-message-container&quot;]/div[@class=&quot;bs-message bottom&quot;]/div[@class=&quot;fade toast message-container theme-new variant-success regular-2 show&quot;]/div[@class=&quot;message-desc&quot;]</value>
      <webElementGuid>4b39b6e4-78bb-4aeb-80dc-ddc797664eab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[7]/div[2]/div/div[2]</value>
      <webElementGuid>ffa08cc3-827e-4074-ac13-7cfcdcb67a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>c95c1ee2-375e-44c8-861e-db4e86d73285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sequence duplicated successfully' or . = 'Sequence duplicated successfully')]</value>
      <webElementGuid>f4203515-216a-4b36-8462-5165e9412d73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
