<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_fab fa-youtube</name>
   <tag></tag>
   <elementGuidId>e3639963-3322-419e-9565-e206890d39f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fab.fa-youtube</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page']/footer/div/div/div[2]/div[2]/div[2]/div/a[4]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>022dd29f-09b3-4b03-bb81-53d85872471d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fab fa-youtube</value>
      <webElementGuid>f6e3a92e-bab2-4e15-9276-aea2a8b629e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5ee07a8c-a05b-4380-b4a8-65b993b354d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/footer[1]/div[@class=&quot;tw-newbrand22&quot;]/div[@class=&quot;container font-sans mx-auto px-4 x:px-0 md:flex&quot;]/div[@class=&quot;flex-1&quot;]/div[@class=&quot;grid grid-cols-1 lg:grid-cols-2&quot;]/div[2]/div[@class=&quot;text-right mb-4&quot;]/a[@class=&quot;inline-block px-3 last:pr-0 text-neutral-800 hover:text-lilac-600 text-lg&quot;]/i[@class=&quot;fab fa-youtube&quot;]</value>
      <webElementGuid>8947bfd9-9609-4399-8e2a-12ba51752701</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/footer/div/div/div[2]/div[2]/div[2]/div/a[4]/i</value>
      <webElementGuid>c95a382c-734a-4aa0-9646-4d6b264214c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/i</value>
      <webElementGuid>3f45c045-d738-4fcf-b67d-35498f5e3e05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
