<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_About</name>
   <tag></tag>
   <elementGuidId>a30f59b9-fdd9-4696-a7c6-6fd9d0f4fa9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > a.nav-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'About')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fb7da801-58d7-4856-ae4c-12fa17c81609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/about-us</value>
      <webElementGuid>08d3a835-7ff9-485f-81b4-02d59e828448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>ae59177f-f686-44ed-a106-7b1cd32539ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>About</value>
      <webElementGuid>700c1f28-e5cc-402f-aaa8-9e3cf38ee5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;w-mod-js w-mod-ix wf-montserrat-i4-active wf-montserrat-i5-active wf-montserrat-i1-active wf-montserrat-i7-active wf-montserrat-i9-active wf-montserrat-i3-active wf-montserrat-i2-active wf-montserrat-i6-active wf-montserrat-i8-active wf-montserrat-n6-active wf-montserrat-n4-active wf-montserrat-n9-active wf-montserrat-n7-active wf-montserrat-n3-active wf-montserrat-n5-active wf-montserrat-n8-active wf-montserrat-n1-active wf-montserrat-n2-active wf-archivo-n5-active wf-archivo-n3-active wf-archivo-n4-active wf-archivo-n6-active wf-active wf-instrumentsans-n4-active&quot;]/body[@class=&quot;body loader-init dark-header loader-hide loaded&quot;]/div[@class=&quot;navbar-logo-left&quot;]/div[@class=&quot;navbar-logo-left-container shadow-three no-bg desktop-header w-nav&quot;]/div[@class=&quot;container-x&quot;]/div[@class=&quot;navbar-wrapper&quot;]/nav[@class=&quot;nav-menu-wrapper w-nav-menu&quot;]/ul[@class=&quot;nav-menu-two w-list-unstyled&quot;]/li[2]/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>7ecc3924-657b-4b61-ae24-86ebf053a0dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'About')]</value>
      <webElementGuid>94884f7a-fbc8-400c-aa67-d89a0d9be7e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/about-us')]</value>
      <webElementGuid>a33b9cf9-1e38-4edf-928a-297ed28241fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>41afd96a-c696-4951-9d09-133114f61184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/about-us' and (text() = 'About' or . = 'About')]</value>
      <webElementGuid>c78672bc-0698-4181-99c4-c753b09f005f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
