<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Contact</name>
   <tag></tag>
   <elementGuidId>61abeb76-62a3-408b-b08b-ea0a544b0412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(6) > a.nav-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Contact')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3b17d27a-df40-4cef-9362-96c011768b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/contact-us</value>
      <webElementGuid>dae61a4f-2d57-4696-b245-da3887dd5346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>f4830220-9b5c-4ef7-99cc-acdee9ab1693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact</value>
      <webElementGuid>1ae5dbf7-2d90-42d4-9b2b-1f8f536103fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;w-mod-js w-mod-ix wf-montserrat-i9-active wf-montserrat-i6-active wf-montserrat-i4-active wf-montserrat-i2-active wf-montserrat-i5-active wf-montserrat-i7-active wf-montserrat-i1-active wf-montserrat-i3-active wf-montserrat-i8-active wf-montserrat-n9-active wf-montserrat-n1-active wf-montserrat-n4-active wf-montserrat-n5-active wf-montserrat-n7-active wf-montserrat-n3-active wf-montserrat-n6-active wf-montserrat-n2-active wf-montserrat-n8-active wf-archivo-n6-active wf-archivo-n3-active wf-archivo-n5-active wf-archivo-n4-active wf-active wf-instrumentsans-n4-active&quot;]/body[@class=&quot;body loader-init dark-header loader-hide loaded&quot;]/div[@class=&quot;navbar-logo-left&quot;]/div[@class=&quot;navbar-logo-left-container shadow-three no-bg desktop-header w-nav&quot;]/div[@class=&quot;container-x&quot;]/div[@class=&quot;navbar-wrapper&quot;]/nav[@class=&quot;nav-menu-wrapper w-nav-menu&quot;]/ul[@class=&quot;nav-menu-two w-list-unstyled&quot;]/li[6]/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>dba3e628-b492-45c5-a7ec-dd76ae4a8e15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Contact')]</value>
      <webElementGuid>d32dc018-a1d8-49c1-839c-8dba8e787d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/contact-us')]</value>
      <webElementGuid>15603a89-6434-4c4e-9365-5c7c7fa54ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>1e871e00-701a-4215-ad6e-1b2985411c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/contact-us' and (text() = 'Contact' or . = 'Contact')]</value>
      <webElementGuid>f966e866-b8cb-4e81-b075-745f8a635a34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
