<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_hdfc-logo-icon</name>
   <tag></tag>
   <elementGuidId>8fa3702c-3857-493f-8a78-df8e219cdb29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.navbar-brand.hidden-xs.cursor-pointer.first-ul-li-logo-url.exclude-me > span.hdfc-logo-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[2]/header/div/div/div/div/div[2]/div/div[3]/div/div/div/div/div/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a3ab51f6-62e9-44a1-b372-896192ee145a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hdfc-logo-icon</value>
      <webElementGuid>054d6937-327c-4f5a-aaa5-00aa09f20468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;lp-page-children bp-area --area&quot;]/header[1]/div[@class=&quot;top-menu&quot;]/div[@class=&quot;row main-nav-container&quot;]/div[@class=&quot;main-header bp-container B-template-hdfc-header container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;bp-area B-template-hdfc-header--area col-lg-9 col-md-8 col-sm-10 col-xs-8&quot;]/div[@class=&quot;bp-widget bp-ui-dragRoot&quot;]/div[@class=&quot;bp-widget-body ng-scope&quot;]/div[@class=&quot;main-nav&quot;]/div[@class=&quot;bp-g-model&quot;]/div[@class=&quot;lp-navbar-advanced ng-scope&quot;]/div[@class=&quot;navbar navbar-inverse navbar-static-top&quot;]/div[@class=&quot;header-menu container-fluid&quot;]/div[@class=&quot;navbar-header clearfix&quot;]/a[@class=&quot;navbar-brand hidden-xs cursor-pointer first-ul-li-logo-url exclude-me&quot;]/span[@class=&quot;hdfc-logo-icon&quot;]</value>
      <webElementGuid>f3ad08bf-62c8-4016-8654-b6c419ed4634</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/header/div/div/div/div/div[2]/div/div[3]/div/div/div/div/div/div/a/span</value>
      <webElementGuid>cb1d735f-f76e-4b2c-be3a-542a21f2de20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/a/span</value>
      <webElementGuid>284c5728-9927-4cfc-87af-54473bf4019f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
