<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tenementNo</name>
   <tag></tag>
   <elementGuidId>6f3b4f9b-657a-4d71-b8d2-760dc39af28a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tenementNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tenementNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6385ae0-6532-4298-ac22-31758f541160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e4b39961-3d51-411b-a0d1-e918e91add4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Tenement No is required.</value>
      <webElementGuid>d900e29f-f1ea-4709-b749-ac236e1b2af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tenementNo</value>
      <webElementGuid>dca029ba-1d90-4d68-bf6a-1c0c610ceaf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tenementNo</value>
      <webElementGuid>6a9507bf-7012-4443-aacb-ce20b261516b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>InputToUpper(this);</value>
      <webElementGuid>748f11e0-db56-4417-b879-e08276cd61b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a7f92a26-1b6b-45df-a61a-58a880a6dee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tenementNo&quot;)</value>
      <webElementGuid>0456ea40-29e2-4a4e-93eb-53ec502412ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tenementNo']</value>
      <webElementGuid>809b2ef5-44f8-4e84-bbb6-a65bcc8fdb01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-2609']/div[2]/div/div/div[2]/div/div[2]/form/div/div/div/div/div/input</value>
      <webElementGuid>a0e18302-e127-4be0-a3cb-71148a5afe08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>dd38d465-e024-420d-9160-0602607ccb2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tenementNo' and @name = 'tenementNo' and @type = 'text']</value>
      <webElementGuid>f21b7a19-7502-4d3d-b875-c4c65325eaf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
