<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_The tenement number is the 15 digits n_602121</name>
   <tag></tag>
   <elementGuidId>8f7ffb61-db68-4966-afaa-d9aa0c3fb09c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='post-2609']/div[2]/div/div/div[2]/div/div[2]/form/div/div/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6248a1bf-ce76-4379-b12b-05ca2b2ce5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field-validation-valid error </value>
      <webElementGuid>cb1860d0-aebb-4649-b222-d321397ade06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The tenement number is the 15 digits number of the following format : 01234567890001T</value>
      <webElementGuid>b6218d77-f7eb-4624-b0c7-a8dd1610a817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-2609&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9&quot;]/div[1]/div[@class=&quot;pagecontent&quot;]/form[1]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;form-horizontal&quot;]/div[@class=&quot;form-group text-center&quot;]/span[@class=&quot;field-validation-valid error&quot;]</value>
      <webElementGuid>b66dc68f-2d47-453b-8d22-53ba71262cc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-2609']/div[2]/div/div/div[2]/div/div[2]/form/div/div/div/div[2]/span</value>
      <webElementGuid>d8fa3420-bd55-44e6-afa9-a356cf5f27d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>edfeef77-bde6-4056-86ce-61ea60f8316e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'The tenement number is the 15 digits number of the following format : 01234567890001T' or . = 'The tenement number is the 15 digits number of the following format : 01234567890001T')]</value>
      <webElementGuid>394744ab-b995-4bd5-b08d-dd2ffb38c256</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
