<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login</name>
   <tag></tag>
   <elementGuidId>473a2688-7bad-4d7d-925e-b5f38ccbf50d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.shd-button.shd-button--primary.shd-button--fullWidth > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[9]/div[2]/div/form/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>589a4c49-5e1e-4bca-921a-afebf90d167c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>c922aa10-0eee-4427-94ef-c12be7563cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;auth&quot;]/div[@class=&quot;auth-wrapper&quot;]/div[@class=&quot;auth-container&quot;]/form[@class=&quot;auth-container--form&quot;]/button[@class=&quot;shd-button shd-button--primary shd-button--fullWidth&quot;]/span[1]</value>
      <webElementGuid>c7305fe6-75dd-49b4-9745-f570694a10c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[9]/div[2]/div/form/button/span</value>
      <webElementGuid>1bbb917c-67fc-4ef1-83a7-2f11e4230395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>6678cff0-5fe6-4b17-b3a0-bf68968e5e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>37022ad5-997b-46da-b3fb-e95e80f006eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
